import forms from '@tailwindcss/forms'
import containerQueries from '@tailwindcss/container-queries'

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        secondary: '#4648d4',
        'on-tertiary-fixed': '#191c1e',
        'on-background': '#0b1c30',
        'surface-dim': '#cbdbf5',
        'surface-tint': '#545f73',
        'surface-container-high': '#dce9ff',
        'inverse-surface': '#213145',
        'surface-container-highest': '#d3e4fe',
        'surface-variant': '#d3e4fe',
        'outline-variant': '#c5c6cd',
        'primary-container': '#1e293b',
        'inverse-on-surface': '#eaf1ff',
        'on-primary-fixed': '#111c2d',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed-variant': '#444749',
        'error-container': '#ffdad6',
        'on-primary-fixed-variant': '#3c475a',
        'on-secondary': '#ffffff',
        'on-tertiary-container': '#8d9092',
        'tertiary-fixed': '#e0e3e5',
        'on-primary': '#ffffff',
        'on-secondary-fixed': '#07006c',
        'tertiary-container': '#26292b',
        'on-primary-container': '#8590a6',
        'primary-fixed': '#d8e3fb',
        'on-secondary-container': '#fffbff',
        'on-error-container': '#93000a',
        'primary-fixed-dim': '#bcc7de',
        'inverse-primary': '#bcc7de',
        'secondary-fixed-dim': '#c0c1ff',
        'on-error': '#ffffff',
        'surface-container': '#e5eeff',
        'on-surface-variant': '#45474c',
        error: '#ba1a1a',
        'on-surface': '#0b1c30',
        outline: '#75777d',
        'surface-container-low': '#eff4ff',
        'on-tertiary': '#ffffff',
        'secondary-container': '#6063ee',
        background: '#f8f9ff',
        'on-secondary-fixed-variant': '#2f2ebe',
        tertiary: '#111516',
        surface: '#f8f9ff',
        'tertiary-fixed-dim': '#c4c7c9',
        'surface-bright': '#f8f9ff',
        'secondary-fixed': '#e1e0ff',
        primary: '#091426',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'stack-sm': '8px',
        'stack-lg': '32px',
        'margin-desktop': '40px',
        'margin-mobile': '16px',
        'stack-md': '16px',
        unit: '4px',
        gutter: '24px',
        'container-max': '1280px',
      },
      fontFamily: {
        'headline-lg': ['Inter'],
        'label-caps': ['JetBrains Mono'],
        'headline-lg-mobile': ['Inter'],
        'display-lg': ['Inter'],
        'title-md': ['Inter'],
        'body-lg': ['Inter'],
        'body-sm': ['Inter'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'title-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
  plugins: [forms, containerQueries],
}
